Fixed linking of cinelerra on ubuntu 13.10 64 bit
Fixed errors:
/usr/bin/ld: filempeg.o: undefined reference to symbol 'lame_encode_buffer_float'
/usr/lib/x86_64-linux-gnu/libmp3lame.so.0: error adding symbols: DSO missing from command line